// Code generated by MockGen. DO NOT EDIT.
// Source: src/internal/domain/short_link/repository.go
//
// Generated by this command:
//
//	mockgen -source=src/internal/domain/short_link/repository.go -package=mocks -destination=src/internal/application/services/mocks/short_link_repository.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	short_link "shortener/src/internal/domain/short_link"

	gomock "go.uber.org/mock/gomock"
)

// MockShortLinkRepository is a mock of ShortLinkRepository interface.
type MockShortLinkRepository struct {
	ctrl     *gomock.Controller
	recorder *MockShortLinkRepositoryMockRecorder
	isgomock struct{}
}

// MockShortLinkRepositoryMockRecorder is the mock recorder for MockShortLinkRepository.
type MockShortLinkRepositoryMockRecorder struct {
	mock *MockShortLinkRepository
}

// NewMockShortLinkRepository creates a new mock instance.
func NewMockShortLinkRepository(ctrl *gomock.Controller) *MockShortLinkRepository {
	mock := &MockShortLinkRepository{ctrl: ctrl}
	mock.recorder = &MockShortLinkRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShortLinkRepository) EXPECT() *MockShortLinkRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockShortLinkRepository) Create(ctx context.Context, shortURL, originalURL string) (*short_link.ShortLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, shortURL, originalURL)
	ret0, _ := ret[0].(*short_link.ShortLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockShortLinkRepositoryMockRecorder) Create(ctx, shortURL, originalURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockShortLinkRepository)(nil).Create), ctx, shortURL, originalURL)
}

// Get mocks base method.
func (m *MockShortLinkRepository) Get(ctx context.Context, shortURL string) (*short_link.ShortLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, shortURL)
	ret0, _ := ret[0].(*short_link.ShortLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockShortLinkRepositoryMockRecorder) Get(ctx, shortURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockShortLinkRepository)(nil).Get), ctx, shortURL)
}
