// Code generated by MockGen. DO NOT EDIT.
// Source: src/internal/domain/visit/repository.go
//
// Generated by this command:
//
//	mockgen -source=src/internal/domain/visit/repository.go -package=mocks -destination=src/internal/application/services/mocks/visit_repository.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	visit "shortener/src/internal/domain/visit"

	gomock "go.uber.org/mock/gomock"
)

// MockVisitRepository is a mock of VisitRepository interface.
type MockVisitRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVisitRepositoryMockRecorder
	isgomock struct{}
}

// MockVisitRepositoryMockRecorder is the mock recorder for MockVisitRepository.
type MockVisitRepositoryMockRecorder struct {
	mock *MockVisitRepository
}

// NewMockVisitRepository creates a new mock instance.
func NewMockVisitRepository(ctrl *gomock.Controller) *MockVisitRepository {
	mock := &MockVisitRepository{ctrl: ctrl}
	mock.recorder = &MockVisitRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVisitRepository) EXPECT() *MockVisitRepositoryMockRecorder {
	return m.recorder
}

// AnalyticsAggregatedByDay mocks base method.
func (m *MockVisitRepository) AnalyticsAggregatedByDay(ctx context.Context, shortURL string) ([]visit.PeriodCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AnalyticsAggregatedByDay", ctx, shortURL)
	ret0, _ := ret[0].([]visit.PeriodCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AnalyticsAggregatedByDay indicates an expected call of AnalyticsAggregatedByDay.
func (mr *MockVisitRepositoryMockRecorder) AnalyticsAggregatedByDay(ctx, shortURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnalyticsAggregatedByDay", reflect.TypeOf((*MockVisitRepository)(nil).AnalyticsAggregatedByDay), ctx, shortURL)
}

// AnalyticsAggregatedByMonth mocks base method.
func (m *MockVisitRepository) AnalyticsAggregatedByMonth(ctx context.Context, shortURL string) ([]visit.PeriodCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AnalyticsAggregatedByMonth", ctx, shortURL)
	ret0, _ := ret[0].([]visit.PeriodCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AnalyticsAggregatedByMonth indicates an expected call of AnalyticsAggregatedByMonth.
func (mr *MockVisitRepositoryMockRecorder) AnalyticsAggregatedByMonth(ctx, shortURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnalyticsAggregatedByMonth", reflect.TypeOf((*MockVisitRepository)(nil).AnalyticsAggregatedByMonth), ctx, shortURL)
}

// AnalyticsAggregatedByUserAgent mocks base method.
func (m *MockVisitRepository) AnalyticsAggregatedByUserAgent(ctx context.Context, shortURL string) ([]visit.UserAgentCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AnalyticsAggregatedByUserAgent", ctx, shortURL)
	ret0, _ := ret[0].([]visit.UserAgentCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AnalyticsAggregatedByUserAgent indicates an expected call of AnalyticsAggregatedByUserAgent.
func (mr *MockVisitRepositoryMockRecorder) AnalyticsAggregatedByUserAgent(ctx, shortURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnalyticsAggregatedByUserAgent", reflect.TypeOf((*MockVisitRepository)(nil).AnalyticsAggregatedByUserAgent), ctx, shortURL)
}

// CreateBatch mocks base method.
func (m *MockVisitRepository) CreateBatch(ctx context.Context, visits []visit.Visit) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreateBatch", ctx, visits)
}

// CreateBatch indicates an expected call of CreateBatch.
func (mr *MockVisitRepositoryMockRecorder) CreateBatch(ctx, visits any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatch", reflect.TypeOf((*MockVisitRepository)(nil).CreateBatch), ctx, visits)
}
